# Generated by Django 5.1.1 on 2024-12-19 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmacargasetpoint',
            name='valor',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
